version: 1.1

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - add_ssh_keys:
        fingerprints:
          - "2f:1e:f4:a3:0f:dd:e6:52:29:e8:b2:38:41:60:df:ac"
      - checkout
      - restore_cache:
          keys:
            - dependencies_project
      - run:
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies_project
      - run:
          name: Build
          command: yarn build
      - run:
          name: Deploy


workflows:
  version: 2
  build_my_project:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
