version: 1.1

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - add_ssh_keys:
          fingerprints:
            - "8f:07:b2:ef:f4:3b:5f:ff:22:1a:82:a3:38:03:1f:1d"
      - checkout
      - restore_cache:
          keys:
            - dependencies_project
      - run:
          name: Install
          command: npm install --registry=https://registry.npm.taobao.org
      - save_cache:
          paths:
            - node_modules
          key: dependencies_project
      - run:
          name: Build
          command: yarn build
      - run:
          name: Chmod Deploy
          command: chmod +x scripts/publish.sh
      - run:
          name: Deploy
          command: scripts/publish.sh

workflows:
  version: 2
  build_my_project:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
